---
# Remote user name
ansible_user: root

# Ansible ssh private key
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Cluster Lab Architecture
centralized_san: false

# GitOps Repo
git_private_repo: false

###################
# Default Gateway
###################
default_gateway: 31.56.39.1

#######################
# DNS configuration
#######################
dns_server: 8.8.8.8
dns_domain: vps.local

############################
# restic backup role variables
############################
restic_clean_service: false
restic_backups_dirs:
  - path: '/etc'
  - path: '/root'
    exclude:
      - pattern: '.cache'
  - path: '/home/{{ ansible_user }}'
    exclude:
      - pattern: '.cache'
      - pattern: '.ansible'
