---
all:
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local
    
    picluster:
      hosts:
        vps1:
          hostname: vps1
          ansible_host: 31.56.39.58
          ip: 31.56.39.58
    
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            vps1:
        k3s_worker:
          hosts:
            vps1:
